.TH "CLEANUPUTILS" 1 "2014-11-25" "Robert L Parker rlp1938@gmail.com"


.SH NAME

.P
\fBcleanuputils\fR \- man page to describe a set of utility programs aimed
at managing a users hard drive space.

.SH SYNOPSIS

.P
There are a number of programs which used together may greatly assist
in the management of files and directories stored in the users home
directory.

.TP
Search programs:

.RS
.IP \(bu 3
\fBbigfiles\fR
.IP \(bu 3
\fBbrokensym\fR
.IP \(bu 3
\fBoldfiles\fR
.IP \(bu 3
\fBduplicates\fR
.RE

.TP
These search from a user input top directory or by default from the
user's home directory. All output is to \fIstdout\fR with error states
reported on \fIstderr\fR.
.TP
And there are file manipulation and/or deletion programs:

.RS
.IP \(bu 3
\fBdelemptydir\fR
.IP \(bu 3
\fBprocessdups\fR
.IP \(bu 3
\fBsetfiletime\fR
.IP \(bu 3
\fBzapfiles\fR
.RE

.TP
Further detail below:

.SH BIGFILES

.P
Lists files in reverse order of size to \fIstdout\fR. Option to specify
minimum size in bytes, kilobytes or megabytes. Default is 1 byte minimum.

.SH BROKENSYM

.P
Lists broken symlinks on \fIstdout\fR.

.SH OLDFILES

.P
Lists files older than an optionally selected date or age to \fIstdout\fR.
The default age is 3 years.

.SH DUPLICATES

.P
Lists duplicated files to \fIstdout\fR. One or more directories may be
input and such directories need not be on the same file system. File
names play no part in selection, rather duplicates are determined by
having the same \fBmd5sum\fR. Any broken symlinks discovered in the search
will be output to \fIstderr\fR.

.SH DELEMPTYDIR

.P
Deletes all empty directories under the optionally input top directory,
or by default the users home directory.

.SH PROCESSDUPS

.P
Using as input a file to which \fBduplicates\fR has been directed this
interactive program lists groups of duplicated files and gives the
option of doing nothing, preserving the content of just one directory
and deleting the other copies, deleting then making links where the
copies were. In this last case the links will be hard if on the same
file system, symlinks otherwise.

.SH SETFILETIME

.P
Using as input a file created by \fBoldfiles\fR, the program will update
times to present time or an optionally selected age or time in the past.
In a typical use scenario some files will be extracted from a list of old files and used as input to \fBzapfiles\fR to remove them and others
will remain to be used as input to \fBsetfiletime\fR to give them a new
lease of life.

.SH ZAPFILES

.P
This program works on a list of files as produced by \fBoldfiles\fR, the
error output of \fBduplicates\fR, or the filed output of \fBbrokensym\fR and
simply deletes them. It does not automatically delete any empty
directories that arise from this activity. Use \fBdelemptydir\fR to take
care of this.

.SH SEE ALSO

.P
\fBbigfiles\fR(1), \fBbrokensym\fR(1), \fBdelemptydir\fR(1), \fBduplicates\fR(1),
\fBoldfiles\fR(1), \fBprocessdups\fR(1), \fBsetfiletime\fR(1), \fBzapfiles\fR(1)

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man cleanuputils.t2t
